project:
  type: book
  output-dir: _output
  resources: 
    - assets/**

book:
  title: "机器学习系统架构师"
  subtitle: "从第一性原理到实际应用的 Vibe Coding 之旅"
  author: "陆海波 上海应用技术大学 经济与管理学院"
  date: today
  language: zh-CN
  page-navigation: true
  chapters:
    - index.qmd
    - part: ch01/index.qmd
      chapters:
        - ch01/1_1_crisis_opportunity.qmd
        - ch01/1_2_player_to_designer.qmd
        - ch01/1_3_vibe_coding_paradigm.qmd
        - ch01/1_4_vibe_coding_practice.qmd
        - ch01/1_5_exercises.qmd
    - part: ch02/index.qmd
      chapters:
        - ch02/2_1_business_challenge.qmd
        - ch02/2_2_definition_framework.qmd
        - ch02/2_3_ml_problem_types.qmd
        - ch02/2_4_vibe_coding_practice.qmd
        - ch02/2_5_exercises.qmd
    - part: ch03/index.qmd
      chapters:
        - ch03/3_1_vector_space.qmd
        - ch03/3_2_probability.qmd
        - ch03/3_3_optimization.qmd
        - ch03/3_4_vibe_coding_practice.qmd
        - ch03/3_5_exercises.qmd
    - part: ch04/index.qmd
      chapters:
        - ch04/4_1_beyond_charts.qmd
        - ch04/4_2_human_vision.qmd
        - ch04/4_3_insight_framework.qmd
        - ch04/4_4_vibe_coding_practice.qmd
        - ch04/4_5_exercises.qmd
    - part: ch05/index.qmd
      chapters:
        - ch05/5_1_business_challenge.qmd
        - ch05/5_2_linear_regression.qmd
        - ch05/5_3_overfitting_regularization.qmd
        - ch05/5_4_xai.qmd
        - ch05/5_5_vibe_coding_practice.qmd
        - ch05/5_6_exercises.qmd
    - part: ch06/index.qmd
      chapters:
        - ch06/6_1_business_challenge.qmd
        - ch06/6_2_probability_vs_geometry.qmd
        - ch06/6_3_kernel_trick.qmd
        - ch06/6_4_xai.qmd
        - ch06/6_5_vibe_coding_practice.qmd
        - ch06/6_6_exercises.qmd
    - part: ch07/index.qmd
      chapters:
        - ch07/7_1_business_challenge.qmd
        - ch07/7_2_decision_tree.qmd
        - ch07/7_3_ensemble_philosophy.qmd
        - ch07/7_4_random_forest.qmd
        - ch07/7_5_gradient_boosting.qmd
        - ch07/7_6_xai_for_trees.qmd
        - ch07/7_7_vibe_coding_practice.qmd
        - ch07/7_8_exercises.qmd
    - part: ch08/index.qmd
      chapters:
        - ch08/8_1_business_challenge.qmd
        - ch08/8_2_kmeans.qmd
        - ch08/8_3_beyond_kmeans.qmd
        - ch08/8_4_clustering_evaluation.qmd
        - ch08/8_5_vibe_coding_practice.qmd
        - ch08/8_6_exercises.qmd
    - part: ch09/index.qmd
      chapters:
        - ch09/9_1_challenge.qmd
        - ch09/9_2_history.qmd
        - ch09/9_3_neuron_activation.qmd
        - ch09/9_4_fully_connected_network.qmd
        - ch09/9_5_training_engine.qmd
        - ch09/9_6_deep_learning_gears.qmd
        - ch09/9_7_vibe_coding_practice.qmd
        - ch09/9_8_exercises.qmd
    - part: ch10/index.qmd
      chapters:
        - ch10/10_1_challenge.qmd
        - ch10/10_2_word_embeddings.qmd
        - ch10/10_3_rag_architecture.qmd
        - ch10/10_4_transformer_attention.qmd
        - ch10/10_5_vibe_coding_practice.qmd
        - ch10/10_6_exercises.qmd
    - part: ch11/index.qmd
      chapters:
        - ch11/11_1_challenge.qmd
        - ch11/11_2_attention_mechanism.qmd
        - ch11/11_3_transformer_architecture.qmd
        - ch11/11_4_vibe_coding_practice.qmd
        - ch11/11_5_exercises.qmd
    - part: ch12/index.qmd
      chapters:
        - ch12/12_1_business_challenge.qmd
        - ch12/12_2_cnn.qmd
        - ch12/12_3_vit.qmd
        - ch12/12_4_vibe_coding_practice.qmd
        - ch12/12_5_exercises.qmd
    - part: ch13/index.qmd
      chapters:
        - ch13/13_1_business_challenge.qmd
        - ch13/13_2_transfer_learning_intro.qmd
        - ch13/13_3_finetuning_techniques.qmd
        - ch13/13_4_transformer_architectures.qmd
        - ch13/13_5_vibe_coding_practice.qmd
        - ch13/13_6_exercises.qmd
    - part: ch14/index.qmd
      chapters:
        - ch14/14_1_business_challenge.qmd
        - ch14/14_2_generative_adversarial_networks.qmd
        - ch14/14_3_diffusion_models.qmd
        - ch14/14_4_autoregressive_models.qmd
        - ch14/14_5_vibe_coding_practice.qmd
        - ch14/14_6_exercises.qmd
    - part: ch15/index.qmd
      chapters:
        - ch15/15_1_business_challenge.qmd
        - ch15/15_2_first_principle.qmd
        - ch15/15_3_rag_foundation.qmd
        - ch15/15_4_chunking.qmd
        - ch15/15_5_vibe_coding_practice.qmd
        - ch15/15_6_exercises.qmd
    - part: ch16/index.qmd
      chapters:
        - ch16/16_1_business_challenge.qmd
        - ch16/16_2_first_principle.qmd
        - ch16/16_3_alignment_paths.qmd
        - ch16/16_4_safe_rlhf.qmd
        - ch16/16_5_vibe_coding_practice.qmd
        - ch16/16_6_exercises.qmd
    - part: ch17/index.qmd
      chapters:
        - ch17/17_1_business_challenge.qmd
        - ch17/17_2_agent_architectures.qmd
        - ch17/17_3_agent_pillars.qmd
        - ch17/17_4_stateful_langgraph.qmd
        - ch17/17_5_vibe_coding_practice.qmd
        - ch17/17_6_exercises.qmd
    - part: ch18/index.qmd
      chapters:
        - ch18/18_1_business_challenge.qmd
        - ch18/18_2_first_principles.qmd
        - ch18/18_3_framework_comparison.qmd
        - ch18/18_4_vibe_coding_practice.qmd
        - ch18/18_5_exercises.qmd
    - part: ch19/index.qmd
      chapters:
        - ch19/19_1_business_challenge.qmd
        - ch19/19_2_first_principle.qmd
        - ch19/19_3_safety_and_alignment.qmd
        - ch19/19_4_embodied_ai.qmd
        - ch19/19_5_governance.qmd
        - ch19/19_6_vibe_coding_practice.qmd
        - ch19/19_7_architects_reflection.qmd
    - part: ch20/index.qmd
      chapters:
        - ch20/20_1_challenge.qmd
        - ch20/20_2_architecture_design.qmd
        - ch20/20_3_vibe_coding_mvp.qmd
        - ch20/20_4_pitch_day.qmd
        - ch20/20_5_reflection.qmd

format:
  html:
    theme: cosmo
    toc: false
    number-sections: false
    fig-cap-location: bottom
    code-fold: false
    code-tools: true
